# Generated by Django 3.2.19 on 2023-07-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='messagestore',
            name='updated_at',
        ),
    ]
