# Generated by Django 3.2.19 on 2023-07-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_auto_20230722_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageStore',
        ),
    ]
