# Generated by Django 3.2.19 on 2023-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_initialquestion_user_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
