# Generated by Django 3.2.19 on 2023-07-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_auto_20230729_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
