# Generated by Django 3.2.19 on 2023-07-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_chatprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPromptParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='coach.chatprompt')),
            ],
        ),
    ]
