# Generated by Django 3.2.20 on 2023-08-12 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_chatpromptparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
