# Generated by Django 3.2.20 on 2023-09-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_alter_userpreferences_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rss_feed', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('PC', 'Podcast'), ('YT', 'Youtube'), ('BL', 'blog')], default='BL', max_length=2)),
            ],
        ),
    ]
