services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis/data

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app


  worker:
    build: .
    command: celery -A backend worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app