databases:
  - name: cyadb
    databaseName: syadb
    user: cyadb
    region: ohio

services:
  - type: web
    name: cyaweb
    env: python
    region: ohio
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 backend.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cyadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: celery-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: celery-redis
          type: redis
          property: port
      - key: PYTHON_VERSION
        value: 3.8.12
  - type: worker
    name: queue
    region: ohio
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A backend worker --loglevel=info --concurrency=4"
    envVars:
      - key: REDIS_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: cyadb
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.8.12
  - type: redis
    name: celery-redis
    region: ohio
    plan: "Starter"
    maxmemoryPolicy: allkeys-lfu # recommended policy for queues
    ipAllowList: [ ] # only allow internal connections