# Generated by Django 3.2.25 on 2024-06-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s3_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('indexed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PR', 'Processing'), ('CP', 'Complete'), ('ER', 'Error')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='uuid',
            field=models.CharField(default='2024-06-19 17:05:40.050273+00:00', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideacollideroutput',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PR', 'Processing'), ('CP', 'Complete'), ('ER', 'Error')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='ideacollideroutput',
            name='uuid',
            field=models.CharField(default='2024-06-19 17:05:50.972165+00:00', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='outline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ideacollideroutput',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
