# Generated by Django 3.2.19 on 2023-06-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkhomey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='talkhomey.Resource'),
        ),
    ]
