# Generated by Django 3.2.19 on 2023-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkhomey', '0002_resource_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
