# Generated by Django 3.2.19 on 2023-05-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
