# Generated by Django 3.2.19 on 2023-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='default_slug',
            field=models.TextField(default='global'),
        ),
    ]
