# Generated by Django 3.2.19 on 2023-05-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_auto_20230529_2057'),
        ('chat', '0004_clientapp_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='search_engine',
        ),
        migrations.AddField(
            model_name='clientapp',
            name='metasearch_engine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app', to='decisions.metasearchengine'),
        ),
        migrations.AddField(
            model_name='source',
            name='metasearch_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='decisions.metasearchengine'),
        ),
    ]
