# Generated by Django 3.2.20 on 2023-09-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cofounder', '0002_businessprofile_founderprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cofounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile', models.TextField()),
                ('profile_image', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofounders', to='cofounder.user')),
            ],
        ),
    ]
