# Generated by Django 3.2.20 on 2023-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofounder', '0003_cofounder'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
