# Generated by Django 3.2.20 on 2023-10-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofounder', '0005_auto_20231012_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='fulltext_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
