# Generated by Django 3.2.24 on 2024-02-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofounder', '0009_answer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(default='details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='taskFor',
            field=models.TextField(default='for this person'),
            preserve_default=False,
        ),
    ]
