# Generated by Django 3.2.24 on 2024-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofounder', '0014_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='email',
            field=models.TextField(default='example@email.com'),
            preserve_default=False,
        ),
    ]
