# Generated by Django 3.2.25 on 2024-04-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20240402_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='uploaded_time',
        ),
    ]
