# Generated by Django 3.2.25 on 2024-04-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_remove_podcastepisode_uploaded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
