# Generated by Django 3.2.25 on 2024-04-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_podcastepisode_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('score', models.FloatField(default=0.0)),
                ('podcast_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcastepisode')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast_episodes', models.ManyToManyField(to='podcast.PodcastEpisode')),
                ('snippets', models.ManyToManyField(to='podcast.PodcastEpisodeSnippet')),
            ],
        ),
    ]
