# Generated by Django 3.2.25 on 2024-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcastepisodesnippet_podcastquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastquery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
