# Generated by Django 3.2.25 on 2024-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_podcastquery_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='podcast_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
