# Generated by Django 3.2.25 on 2024-04-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_alter_podcast_podcast_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastquery',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
