# Generated by Django 3.2.25 on 2024-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('UL', 'Uploaded'), ('PR', 'Processing'), ('CP', 'Complete'), ('ER', 'Error')], default='CR', max_length=2)),
                ('s3_path', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
