# Generated by Django 3.2.25 on 2024-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='name',
            field=models.CharField(default='Pitch deck', max_length=255),
            preserve_default=False,
        ),
    ]
