# Generated by Django 3.2.25 on 2024-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0002_pitchdeck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchdeck',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
