# Generated by Django 3.2.25 on 2024-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0006_pitchdeck_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='analysis_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='report_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
