# Generated by Django 3.2.25 on 2024-04-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0010_company_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='partnerships',
            field=models.TextField(blank=True, null=True),
        ),
    ]
