# Generated by Django 3.2.25 on 2024-04-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0011_company_partnerships'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_opportunity', models.FloatField()),
                ('market_reasoning', models.TextField(blank=True, null=True)),
                ('team', models.FloatField()),
                ('team_reasoning', models.TextField(blank=True, null=True)),
                ('founder_market_fit', models.FloatField()),
                ('founder_market_reasoning', models.TextField(blank=True, null=True)),
                ('product', models.FloatField()),
                ('product_reasoning', models.TextField(blank=True, null=True)),
                ('traction', models.FloatField()),
                ('traction_reasoning', models.TextField(blank=True, null=True)),
                ('final_score', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='prelo.company')),
            ],
        ),
    ]
