# Generated by Django 3.2.25 on 2024-04-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0012_companyscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deck',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='prelo.pitchdeck'),
            preserve_default=False,
        ),
    ]
