# Generated by Django 3.2.25 on 2024-04-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0013_company_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founder_market_fit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
