# Generated by Django 3.2.25 on 2024-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0014_company_founder_market_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyscores',
            name='final_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyscores',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='companyscores',
            name='founder_market_fit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='companyscores',
            name='market_opportunity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='companyscores',
            name='product',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='companyscores',
            name='team',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='companyscores',
            name='traction',
            field=models.FloatField(default=0.0),
        ),
    ]
