# Generated by Django 3.2.25 on 2024-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0016_pitchdeck_target_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.TextField()),
                ('thesis', models.TextField()),
                ('location', models.TextField()),
                ('website', models.TextField()),
                ('name', models.TextField()),
                ('personal_notes', models.TextField()),
            ],
        ),
    ]
