# Generated by Django 3.2.25 on 2024-05-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0017_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_thesis', models.BooleanField()),
                ('matches_location', models.BooleanField()),
                ('matches_sector', models.BooleanField()),
                ('matches_stage', models.BooleanField()),
                ('matches_check_size', models.BooleanField()),
                ('thesis_reasons', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_reports', to='prelo.company')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='prelo.investor')),
            ],
        ),
    ]
