# Generated by Django 3.2.25 on 2024-05-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0018_investorreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorreport',
            name='matches_check_size',
        ),
        migrations.RemoveField(
            model_name='investorreport',
            name='matches_location',
        ),
        migrations.RemoveField(
            model_name='investorreport',
            name='matches_sector',
        ),
        migrations.RemoveField(
            model_name='investorreport',
            name='matches_stage',
        ),
    ]
