# Generated by Django 3.2.25 on 2024-05-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0019_auto_20240509_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorreport',
            name='thesis_match_score',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
