# Generated by Django 3.2.25 on 2024-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0020_investorreport_thesis_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='how_to_overcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='objections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='top_concern',
            field=models.TextField(blank=True, null=True),
        ),
    ]
