# Generated by Django 3.2.25 on 2024-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0022_auto_20240518_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='believe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='concerns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='traction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
