# Generated by Django 3.2.25 on 2024-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0025_auto_20240529_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchdeck',
            name='version',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
