# Generated by Django 3.2.25 on 2024-05-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0026_alter_pitchdeck_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyscores',
            name='company',
        ),
        migrations.AddField(
            model_name='companyscores',
            name='deck',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='prelo.pitchdeck'),
        ),
    ]
