# Generated by Django 3.2.25 on 2024-05-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0027_auto_20240529_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
