# Generated by Django 3.2.25 on 2024-06-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0029_dealmemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='memo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='prelo.dealmemo'),
        ),
    ]
