# Generated by Django 3.2.25 on 2024-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0030_pitchdeckanalysis_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='lookup_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
