# Generated by Django 3.2.25 on 2024-06-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0033_auto_20240604_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoToMarketStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
