# Generated by Django 3.2.25 on 2024-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0034_auto_20240611_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deck_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
