# Generated by Django 3.2.25 on 2024-06-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0035_company_deck_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotomarketstrategy',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='go_to_market', to='prelo.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gotomarketstrategy',
            name='strategy',
            field=models.TextField(default='strategy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompetitorStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('strategy', models.TextField()),
                ('gtm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='prelo.gotomarketstrategy')),
            ],
        ),
    ]
