# Generated by Django 3.2.25 on 2024-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0037_deckreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationDeckUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_uuid', models.CharField(max_length=255)),
                ('deck_uuid', models.CharField(max_length=255)),
            ],
        ),
    ]
