# Generated by Django 3.2.25 on 2024-07-09 13:39
import uuid
from django.db import migrations, models
import django.db.models.deletion

def generate_uuid(apps, schema_editor):
    InvestorReport = apps.get_model('prelo', 'investorreport')
    for row in InvestorReport.objects.all():
        row.uuid = str(uuid.uuid4())
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0038_conversationdeckupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorreport',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_reports', to='prelo.company'),
        ),
        migrations.AddField(
            model_name='investorreport',
            name='recommended_next_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorreport',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorreport',
            name='uuid',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.RunPython(generate_uuid),
        migrations.AlterField(
            model_name='investorreport',
            name='uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
