# Generated by Django 3.2.25 on 2024-07-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0040_investorreport_executive_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='founder_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
