# Generated by Django 3.2.25 on 2024-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0041_pitchdeckanalysis_founder_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorreport',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investorreport',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
