# Generated by Django 3.2.25 on 2024-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0042_auto_20240710_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeckanalysis',
            name='founder_contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
