# Generated by Django 3.2.25 on 2024-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0044_rejectionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyscores',
            name='founder_market_rubric',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscores',
            name='market_rubric',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscores',
            name='product_rubric',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscores',
            name='team_rubric',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscores',
            name='traction_rubric',
            field=models.TextField(blank=True, null=True),
        ),
    ]
