# Generated by Django 3.2.25 on 2024-07-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0045_auto_20240724_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_uuid', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='prelo.investor')),
            ],
        ),
    ]
