# Generated by Django 3.2.25 on 2024-07-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0046_meetingemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeckAnalysisError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('step', models.CharField(max_length=255)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='prelo.pitchdeckanalysis')),
            ],
        ),
    ]
