# Generated by Django 3.2.25 on 2024-08-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0049_invitecoinvestoremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.TextField()),
                ('deck_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('report_uuid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
