# Generated by Django 3.2.25 on 2024-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0050_messagetoconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetoconfirm',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetoconfirm',
            name='conversation_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
