# Generated by Django 3.2.25 on 2024-08-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0051_auto_20240804_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetoconfirm',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
