# Generated by Django 3.2.25 on 2024-09-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0052_messagetoconfirm_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDeckUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_uuid', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('user_ip', models.CharField(max_length=255)),
            ],
        ),
    ]
