# Generated by Django 3.2.25 on 2024-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0054_competitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='feature_matrix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
