# Generated by Django 3.2.25 on 2024-09-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0055_pitchdeck_feature_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='company_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
