# Generated by Django 3.2.25 on 2024-10-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0056_pitchdeck_company_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='website',
        ),
        migrations.AddField(
            model_name='investor',
            name='check_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='industries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='passion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='personal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='thesis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
