# Generated by Django 3.2.25 on 2024-10-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0058_auto_20241003_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
