# Generated by Django 3.2.25 on 2024-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0059_investor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='investor',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_if_not_null'),
        ),
    ]
