# Generated by Django 5.1.2 on 2024-10-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelo', '0060_auto_20241008_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
