# Generated by Django 3.2.25 on 2024-04-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0005_submindclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submindclient',
            name='submind',
        ),
    ]
