# Generated by Django 3.2.25 on 2024-04-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0006_remove_submindclient_submind'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmindClientGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='submind.submindclient')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='submind.goal')),
            ],
        ),
    ]
