# Generated by Django 3.2.25 on 2024-04-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0007_submindclientgoals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmindClientGoals',
        ),
    ]
