# Generated by Django 3.2.25 on 2024-04-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0008_delete_submindclientgoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='submind.submindclient'),
        ),
    ]
