# Generated by Django 3.2.25 on 2024-04-19 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0009_goal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='fast',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubmindTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('inputSchema', models.TextField()),
                ('outputSchema', models.TextField()),
                ('submind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='submind.submind')),
            ],
        ),
    ]
