# Generated by Django 3.2.25 on 2024-04-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0010_auto_20240419_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='submindclient',
            name='collection_name',
            field=models.CharField(default='myaicofounder', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submindclient',
            name='database_name',
            field=models.CharField(default='prelo_memory', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submindclient',
            name='session_suffix',
            field=models.CharField(default='_prelo', max_length=100),
            preserve_default=False,
        ),
    ]
