# Generated by Django 3.2.25 on 2024-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0011_auto_20240430_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submind',
            name='name',
            field=models.TextField(),
        ),
    ]
