# Generated by Django 3.2.25 on 2024-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0013_goal_supporting_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='delegated_goals',
            field=models.ManyToManyField(related_name='delegated_to', to='submind.Goal'),
        ),
    ]
