# Generated by Django 3.2.25 on 2024-05-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0014_goal_delegated_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='delegated_goals',
            field=models.ManyToManyField(related_name='delegated_from', to='submind.Goal'),
        ),
    ]
