# Generated by Django 3.2.25 on 2024-05-02 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0015_alter_goal_delegated_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='delegated_goals',
        ),
        migrations.AddField(
            model_name='goal',
            name='delegated_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_from', to='submind.goal'),
        ),
    ]
