# Generated by Django 3.2.25 on 2024-05-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0017_auto_20240502_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_submind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_started', to='submind.submind')),
                ('to_submind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_received', to='submind.submind')),
            ],
        ),
    ]
