# Generated by Django 3.2.25 on 2024-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0019_auto_20240507_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
