# Generated by Django 3.2.25 on 2024-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0020_conversation_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
