# Generated by Django 3.2.25 on 2024-05-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submind', '0021_message_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='submind.conversation'),
        ),
    ]
