# Generated by Django 3.2.23 on 2024-01-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('input_schema', models.TextField()),
                ('output_schema', models.TextField()),
                ('uuid', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
