# Generated by Django 3.2.18 on 2023-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
