# Generated by Django 3.2.18 on 2023-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_section_embeddings_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='affiliate_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
