# Generated by Django 3.2.18 on 2023-04-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_link_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltext',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulltext', to='search.link'),
        ),
    ]
