# Generated by Django 3.2.18 on 2023-04-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_fulltext_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
