# Generated by Django 3.2.18 on 2023-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_searchablelink_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchablelink',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
