# Generated by Django 3.2.18 on 2023-04-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_alter_searchengine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchablelink',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
