# Generated by Django 3.2.20 on 2023-12-13 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('respond_to', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('respond_to', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='pinecone_id',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='pinecone_id',
            field=models.TextField(default='value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='url',
            field=models.TextField(default='value'),
            preserve_default=False,
        ),
    ]
