# Generated by Django 3.2.20 on 2023-12-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi', '0002_auto_20231213_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='job_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='person',
            name='pinecone_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pinecone_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
