# Generated by Django 3.2.23 on 2023-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi', '0003_auto_20231213_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='uuid',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingrequest',
            name='uuid',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
    ]
