# Generated by Django 3.2.23 on 2023-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agi', '0004_auto_20231213_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingrequest',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomingrequest',
            name='uuid',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='outgoingrequest',
            name='uuid',
            field=models.TextField(unique=True),
        ),
    ]
